PresentationLayer/Controllers/DepartmentController.cs
using AutoMapper;
using BusinessLogicLayer.Interfaces;
using BusinessLogicLayer.Repositories;
using DataAccessLayer.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using PresentationLayer.ViewModels;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;

namespace PresentationLayer.Controllers
{
    [Authorize]

    public class DepartmentController : Controller
    {
        private readonly  IDepartmentRepository _departmemtRepository;
        private readonly IMapper _mapper;

        public DepartmentController(IUnitOfWork unitOfWork,IMapper mapper)
        {
            //_departmemtRepository = new DepartmemtRepository()
            _departmemtRepository = unitOfWork.DepartmentRepository;
            _mapper = mapper;
        }
        
        public async Task<IActionResult> Index(string SearchValue)
        {
            dynamic departments = Enumerable.Empty<Department>();
            if (string.IsNullOrEmpty(SearchValue))
                departments = await _departmemtRepository.GetAll();
            else
                departments = _departmemtRepository.GetDepartmentByName(SearchValue);


            var mappedDepartments = _mapper.Map<IEnumerable<Department>, IEnumerable<DepartmentViewModel>>(departments);
            return View(mappedDepartments);

        }

        public IActionResult Create()
        {

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Create(DepartmentViewModel departmentVM)
        {
            if(ModelState.IsValid)
            {
                var mappedDepartment = _mapper.Map<DepartmentViewModel, Department>(departmentVM);

                await _departmemtRepository.Add(mappedDepartment);
                TempData["Message"] = "Department is Created Seccessfully";
                return RedirectToAction(nameof(Index));
            }
            return View(departmentVM);
        }

        public async Task<IActionResult> Datails(int? id,string ViewName= "Datails")
        {
            if (id == null)
             return NotFound();


            var department = await _departmemtRepository.Get(id.Value);
            if (department == null)
                return NotFound();

            var mappedDepartment = _mapper.Map<Department,DepartmentViewModel>(department);

           
            
            return View(ViewName, mappedDepartment);
        } 



        public async Task<IActionResult> Edit(int? id)
        {

            return await Datails(id,"Edit");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit( DepartmentViewModel departmentVM, [FromRoute] int? ID)
        {
            if(ID.Value  !=departmentVM.Id)
                return BadRequest();

           if(ModelState.IsValid)
            {
                try
                {
                    var mappedDepartment = _mapper.Map<DepartmentViewModel, Department>(departmentVM);

                    await _departmemtRepository.Update(mappedDepartment);
                    return RedirectToAction(nameof(Index));
                }
                catch (System.Exception)
                {
                    //log in database
                    //friendly message
                    //ModelState.AddModelError("",ex.Message);
                    return View(departmentVM);
                    
                }
            }
            return View();
        }

        public async Task<IActionResult> Delete(int? id)
        {
            return await Datails(id, "Delete");
        }

        [HttpPost]
        public async Task<IActionResult> Delete([FromRoute] int? id,DepartmentViewModel departmentVM) 
        {
            if(id.Value!=departmentVM.Id)
                return BadRequest();

            try
            {
                var mappedDepartment = _mapper.Map<DepartmentViewModel, Department>(departmentVM);

                await _departmemtRepository.Delete(mappedDepartment);
                return RedirectToAction(nameof(Index));
            }
            catch (System.Exception)
            {

                return View(departmentVM);
            }
           
        }
    }
}

PresentationLayer/Controllers/EmployeeController.cs
using AutoMapper;
using BusinessLogicLayer.Interfaces;
using DataAccessLayer.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PresentationLayer.Helpers;
using PresentationLayer.ViewModels;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PresentationLayer.Controllers
{
    [Authorize]

    public class EmployeeController : Controller
    {
        private readonly IEmployeeRepository _employeeRepository;
        private readonly IDepartmentRepository _departmemtRepository;
        private readonly IMapper _mapper;

        public EmployeeController(IUnitOfWork unitOfWork, IMapper mapper)
        {
            //_employeeRepository = new employeeRepository()
            _employeeRepository = unitOfWork.EmployeeRepository;
            _departmemtRepository = unitOfWork.DepartmentRepository;
            _mapper = mapper;
        }
        public async Task<IActionResult> Index(string SearchValue)
        {
            var employees = Enumerable.Empty<Employee>();
            if (string.IsNullOrEmpty(SearchValue))
                employees =await _employeeRepository.GetAll();
            else
                employees = _employeeRepository.GetEmployeesByName(SearchValue);


            var mappedEmps = _mapper.Map<IEnumerable<Employee>, IEnumerable<EmployeeViewModel>>(employees);
            return View(mappedEmps);

        }

        public IActionResult Create()
        {
            //ViewBag.Departments=_departmemtRepository.GetAll();
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(EmployeeViewModel employeeVM)
        {
            if (ModelState.IsValid)
            {
                if (employeeVM.Image != null)
                    employeeVM.ImageName = DocumentSettings.UploadFile(employeeVM.Image, "images");

                var mappedEmp = _mapper.Map<EmployeeViewModel, Employee>(employeeVM);
                await _employeeRepository.Add(mappedEmp);
                TempData["Message"] = "Employee is Created Seccessfully";

                return RedirectToAction(nameof(Index));
            }
            return View(employeeVM);
        }

        public async Task<IActionResult> Datails(int? id, string ViewName = "Datails")
        {
            if (id == null)
                return NotFound();


            var employee = await _employeeRepository.Get(id.Value);

            if (employee == null)
                return NotFound();
            var mappedEmp = _mapper.Map<Employee, EmployeeViewModel>(employee);

            TempData["ImageName"] = mappedEmp.ImageName;
             
            return View(ViewName, mappedEmp);
        }



        public async Task<IActionResult> Edit(int? id)
        {
            //ViewBag.Departments = _departmemtRepository.GetAll();
            return await Datails(id, "Edit");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EmployeeViewModel employeeVM, [FromRoute] int? ID)
        {
            if (ID.Value != employeeVM.Id)
                return BadRequest();

            if (ModelState.IsValid)
            {
                try
                {
                    if (employeeVM.Image != null)
                        employeeVM.ImageName = DocumentSettings.UploadFile(employeeVM.Image, "images");

                    var mappedEmp = _mapper.Map<EmployeeViewModel, Employee>(employeeVM);
                   await _employeeRepository.Update(mappedEmp);
                    return RedirectToAction(nameof(Index));
                }
                catch (System.Exception)
                {
                    //log in database
                    //friendly message
                    //ModelState.AddModelError("",ex.Message);
                    return View(employeeVM);

                }
            }
            return View();
        }

        public async Task<IActionResult> Delete(int? id)
        {
            return await Datails(id, "Delete");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete([FromRoute] int? id, EmployeeViewModel employeeVM)
        {
            if (id.Value != employeeVM.Id)
                return BadRequest();

            try
            {
                var mappedEmp = _mapper.Map<EmployeeViewModel, Employee>(employeeVM);

                int count = await _employeeRepository.Delete(mappedEmp);

                if (count > 0 && employeeVM.ImageName != null)
                   DocumentSettings.DeleteFile(employeeVM.ImageName, "images");


                return RedirectToAction(nameof(Index));
            }
            catch (System.Exception)
            {

                return View(employeeVM);
            }

        }
    }
}

PresentationLayer/Controllers/RoleController.cs
using DataAccessLayer.Entities;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace PresentationLayer.Controllers
{
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;

        public RoleController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }


        public async Task<IActionResult> Index(string SearchValue)
        {
            var roles = Enumerable.Empty<IdentityRole>().ToList();
            if (string.IsNullOrEmpty(SearchValue))
                roles.AddRange(_roleManager.Roles);
            else
                roles.Add(await _roleManager.FindByNameAsync(SearchValue));



            return View(roles);

        }

        public IActionResult Create()
        {
            //ViewBag.Departments=_departmemtRepository.GetAll();
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(IdentityRole Role)
        {
            if (ModelState.IsValid)
            {
                await _roleManager.CreateAsync(Role);

                return RedirectToAction(nameof(Index));
            }
            return View(Role);
        }

        public async Task<IActionResult> Datails(string id, string ViewName = "Datails")
        {
            if (id == null)
                return NotFound();

            var role = await _roleManager.FindByIdAsync(id);

            if (role == null)
                return NotFound();

            return View(ViewName, role);
        }



        public async Task<IActionResult> Edit(string id)
        {
            //ViewBag.Departments = _departmemtRepository.GetAll();
            return await Datails(id, "Edit");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(IdentityRole UpdatedRole, [FromRoute] string Id)
        {
            if (Id != UpdatedRole.Id)
                return BadRequest();

            if (ModelState.IsValid)
            {
                try
                {
                    var role = await _roleManager.FindByIdAsync(Id);
                    role.Name = UpdatedRole.Name;


                    await _roleManager.UpdateAsync(role);
                    return RedirectToAction(nameof(Index));
                }
                catch (System.Exception)
                {
                    //log in database
                    //friendly message
                    //ModelState.AddModelError("",ex.Message);
                    return View(UpdatedRole);

                }
            }
            return View();
        }

        public async Task<IActionResult> Delete(string id)
        {
            return await Datails(id, "Delete");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete([FromRoute] string Id, IdentityRole DeletedRole)
        {
            if (Id != DeletedRole.Id)
                return BadRequest();

            try
            {
                var role = await _roleManager.FindByIdAsync(Id);
                await _roleManager.DeleteAsync(role);
                return RedirectToAction(nameof(Index));
            }
            catch (System.Exception)
            {

                return View(DeletedRole);
            }

        }
    }
}

PresentationLayer/Controllers/UserController.cs
using DataAccessLayer.Entities;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PresentationLayer.Helpers;
using PresentationLayer.ViewModels;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PresentationLayer.Controllers
{
    public class UserController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        public UserController(UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
        }

        public async Task<IActionResult> Index(string SearchValue)
        {
            var users = Enumerable.Empty<ApplicationUser>().ToList();
            if (string.IsNullOrEmpty(SearchValue))
                users.AddRange( _userManager.Users);
            else
                users.Add(await _userManager.FindByEmailAsync(SearchValue));


           
            return View(users);

        }

        //public IActionResult Create()
        //{
        //    //ViewBag.Departments=_departmemtRepository.GetAll();
        //    return View();
        //}
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create(EmployeeViewModel employeeVM)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        if (employeeVM.Image != null)
        //            employeeVM.ImageName = DocumentSettings.UploadFile(employeeVM.Image, "images");

        //        var mappedEmp = _mapper.Map<EmployeeViewModel, Employee>(employeeVM);
        //        await _employeeRepository.Add(mappedEmp);
        //        TempData["Message"] = "Employee is Created Seccessfully";

        //        return RedirectToAction(nameof(Index));
        //    }
        //    return View(employeeVM);
        //}

        public async Task<IActionResult> Datails(string id, string ViewName = "Datails")
        {
            if (id == null)
                return NotFound();

            var user = await _userManager.FindByIdAsync(id);

            if (user == null)
                return NotFound();
         
            return View(ViewName, user);
        }



        public async Task<IActionResult> Edit(string id)
        {
            //ViewBag.Departments = _departmemtRepository.GetAll();
            return await Datails(id, "Edit");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ApplicationUser UpdatedUser, [FromRoute] string Id)
        {
            if (Id != UpdatedUser.Id)
                return BadRequest();

            if (ModelState.IsValid)
            {
                try
                {
                    var user = await _userManager.FindByIdAsync(Id);
                    user.UserName=UpdatedUser.UserName;
                    user.PhoneNumber=UpdatedUser.PhoneNumber;

                    await _userManager.UpdateAsync(user);
                    return RedirectToAction(nameof(Index));
                }
                catch (System.Exception)
                {
                    //log in database
                    //friendly message
                    //ModelState.AddModelError("",ex.Message);
                    return View(UpdatedUser);

                }
            }
            return View();
        }

        public async Task<IActionResult> Delete(string id)
        {
            return await Datails(id, "Delete");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete([FromRoute] string Id, ApplicationUser DeletedUser)
        {
            if (Id != DeletedUser.Id)
                return BadRequest();

            try
            {
                var user = await _userManager.FindByIdAsync(Id);
                await _userManager.DeleteAsync(user);
                return RedirectToAction(nameof(Index));
            }
            catch (System.Exception)
            {

                return View(DeletedUser);
            }

        }
    }
}

PresentationLayer/Views/Shared/_AuthLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>@ViewData["Title"] - PresentationLayer</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
    <!-- Font Icon -->
    <link rel="stylesheet" href="~/fonts/material-icon/css/material-design-iconic-font.min.css">

    <!-- Main css -->
    <link rel="stylesheet" href="~/css/Style.css">
</head>
<body>

    <div class="main">

       @RenderBody()
     
    </div>

    <!-- JS -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <script src="~/js/main.js"></script> 
    @await RenderSectionAsync("ValidationScriptSection", required: false)

</body>
</html>

PresentationLayer/Views/Shared/_ButtonsPartailView.cshtml
@model string

@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<td>
    <a asp-action="Datails" asp-route-Id="@Model" class="btn btn-warning">

        <i class="fas fa-eye"></i>   Datails
    </a>
</td>
<td>
    <a asp-action="Edit" asp-route-Id="@Model" class="btn btn-success">

        <i class="fas fa-edit"></i>   Update
    </a>
</td>
<td>
    <a asp-action="Delete" asp-route-Id="@Model" class="btn btn-danger">

        <i class="fas fa-trash"></i>   Delete
    </a>
</td>

PresentationLayer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PresentationLayer</title>
   
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PresentationLayer</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Department</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employee</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                        </li>

                    </ul>
                    <form class="d-flex">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item ">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Roles</a>
                            </li>
                            <li class="nav-item ">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="SignOut">SignOut</a>
                            </li>
                        </ul>
                       
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - PresentationLayer - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("ValidationScriptSection", required: false)
</body>
</html>